version: '3.8'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password12*
      - POSTGRES_DB=DiscountDb
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1434:1433"
    user: root
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    user: root
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - IdentityServerURL=http://duendeis.api
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "2911:80"
    depends_on:
      - catalogdb
  duendeis.api:
    container_name: duendeis.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IssuerURI=http://duendeis.api
      - "ConnectionStrings:Default=Server=identitydb,1433;Database=IdentityDb;User ID=sa;Password=Password12*;Integrated Security=False;TrustServerCertificate=true"
    ports:
      - "2901:80"
    depends_on:
      - identitydb
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://duendeis.api
      - RedisSettings:Host=basketdb
      - RedisSettings:Port=6379
    ports:
      - "2913:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://duendeis.api
    ports:
      - "2912:80"
    volumes:
      - type: bind
        source: C:\Users\Asus\Desktop\photos
        target: /app/wwwroot/photos
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://duendeis.api
      - "ConnectionStrings:PostgreSql=User ID=admin;Password=Password12*;Server=discountdb;Port=5432;Database=DiscountDb;Integrated Security=true;Pooling=true"
    ports:
      - "2914:80"
    depends_on:
      - discountdb
  fakepayment.api:
    container_name: fakepayment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://duendeis.api
      - RabbitMQUrl=rabbitmq
    ports:
      - "2916:80"
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://duendeis.api
      - RabbitMQUrl=rabbitmq
      - "ConnectionStrings:MsSql=Server=orderdb,1433;Database=OrderDb;User ID=sa;Password=Password12*;Integrated Security=False;TrustServerCertificate=true"
    ports:
      - "2915:80"
    depends_on:
      - orderdb
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerURL=http://duendeis.api
    ports:
      - "2900:80"